### ISSUE TITLE
Couldn\'t resolve parser "php"

### ISSUE THREAD

**Issue by HDVinnie** [shufo/blade-formatter#1]
```
{ path: 'resources/views/user/filters/unsatisfieds.blade.php',
  message: 'Couldn\'t resolve parser "php"',
  error: Error: Couldn't resolve parser "php"
    at resolveParser$1 (/var/www/html/node_modules/blade-formatter/node_modules/prettier/index.js:10600:15)
    at normalize (/var/www/html/node_modules/blade-formatter/node_modules/prettier/index.js:10693:19)
    at formatWithCursor (/var/www/html/node_modules/blade-formatter/node_modules/prettier/index.js:14161:12)
    at /var/www/html/node_modules/blade-formatter/node_modules/prettier/index.js:42756:15
    at Object.format (/var/www/html/node_modules/blade-formatter/node_modules/prettier/index.js:42775:12)
    at prettifyPhpContentWithUnescapedTags (/var/www/html/node_modules/blade-formatter/src/util.js:79:25)
    at Proxy.formatAsPhp (/var/www/html/node_modules/blade-formatter/src/util.js:116:20)
    at Formatter.formatContent (/var/www/html/node_modules/blade-formatter/src/formatter.js:29:8)
    at util.readFile.then.then.content (/var/www/html/node_modules/blade-formatter/src/main.js:61:52)
    at <anonymous> }
```

This error is generated after running `node_modules/.bin/blade-formatter --write resources/**/*.blade.php`

**Comment by HDVinnie** [comment]
Ok I managed to get past that error by instead installing it globally with NPM. Now on some files I'm getting.

```{ path: 'resources/views/user/profile.blade.php',
  message: 'Parse error: cannot parse file for some reason.(e.g. inline blade comment block, unrecognized token, inline php call)',
  error: Error: Parse error: cannot parse file for some reason.(e.g. inline blade comment block, unrecognized token, inline php call)
    at Formatter.processTokenizeResult (/usr/lib/node_modules/blade-formatter/src/formatter.js:139:13)
    at Formatter.processLine (/usr/lib/node_modules/blade-formatter/src/formatter.js:81:10)
    at Formatter.formatTokenizedLines (/usr/lib/node_modules/blade-formatter/src/formatter.js:70:12)
    at registry.loadGrammar.then.then.tokenizedLines (/usr/lib/node_modules/blade-formatter/src/formatter.js:57:14)
    at <anonymous> }```
