### ISSUE TITLE
Can't install blade-formatter@1.10.5

### ISSUE THREAD

**Issue by kyori19** [shufo/blade-formatter#235]
## Expected Behavior
Install finishes without any errors

## Current Behavior

```
root@a7a28e2dfaed:/# npm install -g blade-formatter 
npm ERR! code 128
npm ERR! Command failed: git checkout b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
npm ERR! fatal: reference is not a tree: b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-30T08_34_33_019Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'blade-formatter'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose npm-session 8ffa9cff2ba01e2b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/blade-formatter 102ms
8 http fetch GET 200 https://registry.npmjs.org/blade-formatter/-/blade-formatter-1.10.5.tgz 60ms
9 silly pacote tag manifest for blade-formatter@latest fetched in 175ms
10 timing stage:loadCurrentTree Completed in 189ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule blade-formatter@1.10.5 checking installable status
18 http fetch GET 200 https://registry.npmjs.org/chalk 62ms
19 http fetch GET 200 https://registry.npmjs.org/glob 107ms
20 http fetch GET 200 https://registry.npmjs.org/lodash 108ms
21 http fetch GET 200 https://registry.npmjs.org/detect-indent 112ms
22 http fetch GET 200 https://registry.npmjs.org/concat-stream 122ms
23 http fetch GET 200 https://registry.npmjs.org/chalk/-/chalk-4.1.0.tgz 64ms
24 http fetch GET 200 https://registry.npmjs.org/ignore 125ms
25 http fetch GET 200 https://registry.npmjs.org/js-beautify 126ms
26 http fetch GET 200 https://registry.npmjs.org/php-parser 130ms
27 silly pacote range manifest for chalk@^4.1.0 fetched in 141ms
28 silly resolveWithNewModule chalk@4.1.0 checking installable status
29 http fetch GET 200 https://registry.npmjs.org/esm 140ms
30 http fetch GET 200 https://registry.npmjs.org/glob/-/glob-7.1.6.tgz 38ms
31 silly pacote range manifest for glob@^7.1.4 fetched in 163ms
32 silly resolveWithNewModule glob@7.1.6 checking installable status
33 http fetch GET 200 https://registry.npmjs.org/concat-stream/-/concat-stream-2.0.0.tgz 66ms
34 http fetch GET 200 https://registry.npmjs.org/detect-indent/-/detect-indent-6.0.0.tgz 72ms
35 http fetch GET 200 https://registry.npmjs.org/ignore/-/ignore-5.1.8.tgz 61ms
36 silly pacote range manifest for concat-stream@^2.0.0 fetched in 197ms
37 silly resolveWithNewModule concat-stream@2.0.0 checking installable status
38 silly pacote range manifest for detect-indent@^6.0.0 fetched in 199ms
39 silly resolveWithNewModule detect-indent@6.0.0 checking installable status
40 silly pacote range manifest for ignore@^5.1.8 fetched in 197ms
41 silly resolveWithNewModule ignore@5.1.8 checking installable status
42 http fetch GET 200 https://registry.npmjs.org/vscode-oniguruma 108ms
43 http fetch GET 200 https://registry.npmjs.org/php-parser/-/php-parser-3.0.2.tgz 138ms
44 http fetch GET 200 https://registry.npmjs.org/js-beautify/-/js-beautify-1.13.5.tgz 142ms
45 http fetch GET 200 https://registry.npmjs.org/esm/-/esm-3.2.25.tgz 135ms
46 http fetch GET 200 https://registry.npmjs.org/prettier 137ms
47 silly pacote range manifest for php-parser@^3.0.0-prerelease.9 fetched in 281ms
48 silly pacote range manifest for js-beautify@^1.10.2 fetched in 284ms
49 silly resolveWithNewModule php-parser@3.0.2 checking installable status
50 silly resolveWithNewModule js-beautify@1.13.5 checking installable status
51 http fetch GET 200 https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz 168ms
52 silly pacote range manifest for esm@^3.2.25 fetched in 288ms
53 silly resolveWithNewModule esm@3.2.25 checking installable status
54 silly pacote range manifest for lodash@^4.17.19 fetched in 288ms
55 silly resolveWithNewModule lodash@4.17.21 checking installable status
56 http fetch GET 200 https://registry.npmjs.org/yargs 96ms
57 http fetch GET 200 https://registry.npmjs.org/yargs/-/yargs-15.4.1.tgz 76ms
58 silly pacote range manifest for yargs@^15.3.0 fetched in 183ms
59 silly resolveWithNewModule yargs@15.4.1 checking installable status
60 http fetch GET 200 https://registry.npmjs.org/vscode-oniguruma/-/vscode-oniguruma-1.3.1.tgz 104ms
61 silly pacote version manifest for vscode-oniguruma@1.3.1 fetched in 221ms
62 silly resolveWithNewModule vscode-oniguruma@1.3.1 checking installable status
63 http fetch GET 200 https://registry.npmjs.org/prettier/-/prettier-2.2.1.tgz 442ms
64 silly pacote range manifest for prettier@^2.2.0 fetched in 586ms
65 silly resolveWithNewModule prettier@2.2.1 checking installable status
66 http fetch GET 200 https://registry.npmjs.org/vscode-textmate 843ms
67 http fetch GET 200 https://registry.npmjs.org/vscode-textmate/-/vscode-textmate-4.4.0.tgz 45ms
68 silly pacote range manifest for vscode-textmate@^4.2.2 fetched in 892ms
69 silly resolveWithNewModule vscode-textmate@4.4.0 checking installable status
70 info lifecycle @prettier/plugin-php@0.16.1~prepack: @prettier/plugin-php@0.16.1
71 info lifecycle @prettier/plugin-php@0.16.1~postpack: @prettier/plugin-php@0.16.1
72 silly pacote git manifest for @prettier/plugin-php@github:prettier/plugin-php#ed00e2a07851cfacba0f8648dc7b209be6b9e6b9 fetched in 3923ms
73 silly resolveWithNewModule @prettier/plugin-php@0.16.1 checking installable status
74 http fetch GET 200 https://registry.npmjs.org/linguist-languages 153ms
75 http fetch GET 200 https://registry.npmjs.org/mem 154ms
76 http fetch GET 200 https://registry.npmjs.org/linguist-languages/-/linguist-languages-7.13.0.tgz 55ms
77 http fetch GET 200 https://registry.npmjs.org/mem/-/mem-8.1.0.tgz 54ms
78 silly pacote range manifest for linguist-languages@^7.5.1 fetched in 212ms
79 silly resolveWithNewModule linguist-languages@7.13.0 checking installable status
80 silly pacote range manifest for mem@^8.0.0 fetched in 213ms
81 silly resolveWithNewModule mem@8.1.0 checking installable status
82 silly fetchPackageMetaData error for php-parser@github:czosel/php-parser#b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa Command failed: git checkout b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
82 silly fetchPackageMetaData fatal: reference is not a tree: b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
83 timing stage:rollbackFailedOptional Completed in 1ms
84 timing stage:runTopLevelLifecycles Completed in 7795ms
85 verbose stack Error: Command failed: git checkout b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
85 verbose stack fatal: reference is not a tree: b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
85 verbose stack
85 verbose stack     at ChildProcess.exithandler (child_process.js:308:12)
85 verbose stack     at ChildProcess.emit (events.js:314:20)
85 verbose stack     at maybeClose (internal/child_process.js:1021:16)
85 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
86 verbose cwd /
87 verbose Linux 5.4.0-67-generic
88 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "blade-formatter"
89 verbose node v12.19.0
90 verbose npm  v6.14.8
91 error code 128
92 error Command failed: git checkout b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
92 error fatal: reference is not a tree: b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa
93 verbose exit [ 1, true ]
```

## Possible Solution
Stop using `prettier/plugin-php#ed00e2a07851cfacba0f8648dc7b209be6b9e6b9` which uses `czosel/php-parser#b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa`.
Maintainer of `czosel/php-parser` removed [that commit](https://github.com/czosel/php-parser/commit/b55446b48a4a588e8b62c7f9085ce0e7cb3b70fa) from GitHub.

## Steps to Reproduce
1. Run `npm install blade-formatter@1.10.5`

## Context (Environment)
```
npm@6.14.8
node@v12.19.0
```

**Comment by shufo** [comment]
Thank you so much to notified @kyori19! You saved my day.
Just released [v1.10.6]( https://www.npmjs.com/package/blade-formatter/v/1.10.6) using backup commit hash on my [fork](https://github.com/shufo/plugin-php/commit/12343a1f4b5a59cf7e4382d4314c1c86ade90603) with this issue fixed.
