### ISSUE TITLE
Doesn't work with short php tag

### ISSUE THREAD

**Issue by vladyslavstartsev** [shufo/blade-formatter#56]
## Expected Behavior

This should be ignored
```php
<th><?= $userName ?></th>
```

## Current Behavior

```text
{ path:
   '../Modules/Admin/AdminDefault/Resources/views/translation/1.blade.php',
  message:
   "Parse Error : syntax error, unexpected '}', expecting ';' on line 1\n\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[33m<\u001b[39m\u001b[33mth\u001b[39m\u001b[33m>\u001b[39m\u001b[33m<\u001b[39m\u001b[33m?\u001b[39m\u001b[33m=\u001b[39m $uesrName }}\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mth\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m               \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m\u001b[0m",
  error:
   { SyntaxError: Parse Error : syntax error, unexpected '}', expecting ';' on line 1
   > 1 | <th><?= $userName }}</th>
       |                ^
     2 | 
       at parser.raiseError (/node_modules/php-parser/src/parser.js:319:17)
       at parser.error (/node_modules/php-parser/src/parser.js:364:15)
       at parser.expectEndOfStatement (/node_modules/php-parser/src/parser.js:455:10)
       at parser.read_statement (/node_modules/php-parser/src/parser/statement.js:266:14)
       at parser.read_top_statement (/node_modules/php-parser/src/parser/statement.js:71:21)
       at parser.read_start (/node_modules/php-parser/src/parser/main.js:18:19)
       at parser.parse (/node_modules/php-parser/src/parser.js:277:23)
       at engine.parseCode (/node_modules/php-parser/src/index.js:167:22)
       at Object.parse (/node_modules/blade-formatter/node_modules/@prettier/plugin-php/src/parser.js:30:57)
       at Object.parse (/node_modules/blade-formatter/node_modules/prettier/index.js:9739:19)
     fileName: 'eval',
     loc: { start: [Object] },
     codeFrame:
      '\u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 1 | \u001b[39m\u001b[33m<\u001b[39m\u001b[33mth\u001b[39m\u001b[33m>\u001b[39m\u001b[33m<\u001b[39m\u001b[33m?\u001b[39m\u001b[33m=\u001b[39m $userName }}\u001b[33m<\u001b[39m\u001b[33m/\u001b[39m\u001b[33mth\u001b[39m\u001b[33m>\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m   | \u001b[39m               \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n\u001b[0m \u001b[90m 2 | \u001b[39m\u001b[0m' } }

```

## Possible Solution

short echo tag should be legal

## Steps to Reproduce

1. create `tmp.blade.php`
2. add `<th><?= $userName ?></th>` to this file
3.`node_modules/.bin/blade-formatter -d -c tmp.blade.php`
4. see exception

## Context (Environment)

Trying to beautify https://github.com/barryvdh/laravel-translation-manager/blob/master/resources/views/index.php

**Comment by shufo** [comment]
Hi I just Fixed in #99 and includes this fix in [1.2.2](https://www.npmjs.com/package/blade-formatter/v/1.2.2).
