### ISSUE TITLE
Error on @unless(auth()->user()->hasVerifiedEmail())

### ISSUE THREAD

**Issue by sanskar-mk2** [shufo/blade-formatter#686]
## Steps to Reproduce

```
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <p>You're logged in!</p>
                    @unless(auth()->user()->hasVerifiedEmail())
                        <p>Please check and verify your email to access the system</p>
                    @endunless
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

```

## Error

```
message: "Parse Error : syntax error, unexpected ';' on line 1\n" +       
    '> 1 | <?php echo auth()->user()->hasVerifiedEmail(), ?>\n' +
    '    |                                               ^',
  error: SyntaxError: Parse Error : syntax error, unexpected ';' on line 1  
  > 1 | <?php echo auth()->user()->hasVerifiedEmail(), ?>
      |                                               ^
      at $.raiseError (E:\tall\ndis\node_modules\@prettier\plugin-php\standalone.js:4:101152)
      at $.error (E:\tall\ndis\node_modules\@prettier\plugin-php\standalone.js:4:101792)
```

**Comment by shufo** [comment]
Thanks @sanskar-mk2 
Fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.27.4
