### ISSUE TITLE
[Formatting Bug]:  "Parse Error : syntax error, unexpected '!', expecting ';' on line 1\n" +

### ISSUE THREAD

**Issue by francoism90** [shufo/blade-formatter#796]
### Version

1.32.9

### Template before formatting

```blade
<div>
    <p>{{!! $item->description !!}}</p>
</div>
```

### Template after formatting

```blade
<div>
    <p>{{!! $item->description !!}}</p>
</div>
```

### Expected Behaviour

No error

### Relevant log output

```blade
{
  path: 'item.blade.php',
  message: "Parse Error : syntax error, unexpected '!', expecting ';' on line 1\n" +
    '> 1 | <?php echo !! $item->description !! ?>\n' +
    '    |                                 ^',
  error: SyntaxError: Parse Error : syntax error, unexpected '!', expecting ';' on line 1
  > 1 | <?php echo !! $item->description !! ?>
      |                                 ^
      at $.raiseError (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:101799)
      at $.error (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:102439)
      at $.expectEndOfStatement (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:103535)
      at $.read_statement (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:85615)
      at $.read_top_statement (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:82471)
      at $.read_start (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:72049)
      at $.parse (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:101183)
      at fs.parseCode (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:128808)
      at Object.Ns [as parse] (/Users/user/Code/project/node_modules/@prettier/plugin-php/standalone.js:3:129655)
      at Object.h [as parse] (/Users/user/Code/project/node_modules/prettier/standalone.js:40:1337) {
    fileName: 'eval',
    loc: { start: [Object] },
    codeFrame: '> 1 | <?php echo !! $item->description !! ?>\n' +
      '    |                                 ^'
  }
}
```

**Comment by francoism90** [comment]
Command:
```
blade-formatter --write src/**/*.blade.php
```

**Comment by francoism90** [comment]
Oops!
```php
{{!! __('Foo') !!}}
```

Should be:
```php
{!! __('Foo') !!}
```

**Comment by shufo** [comment]
That syntax parse error is happened often so maybe we should add an explicit error message for similar syntax error to improve message.

e.g.

```blade
Syntax Error: item.blade.php 

Invalid Syntax. `{{!! $some !!}}` on line 55
         
You mean `{!! $some !!}` ?
```

Thanks for taking time to create the feedback! @francoism90

**Comment by francoism90** [comment]
@shufo No problem. :)

Thanks for creating and maintaining this package!
