### ISSUE TITLE
How to interpret this error?

### ISSUE THREAD

**Issue by bilogic** [shufo/blade-formatter#869]
### Description
```BASH
# /usr/bin/blade-formatter --no-multiple-empty-lines --sort-html-attributes code-guide --sort-tailwindcss-classes true /home/projects/example/current/resources/views/pages/central/index.blade.php

Errors:

{
  path: '../../home/projects/example/current/resources/views/pages/central/index.blade.php',
  message: "Unexpected token 'export'",
  error: /home/projects/example/current/tailwind.config.js:2
  export default {
  ^^^^^^

  SyntaxError: Unexpected token 'export'
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1175:20)
      at Module._compile (node:internal/modules/cjs/loader:1219:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
      at Module.load (node:internal/modules/cjs/loader:1113:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at Module.require (node:internal/modules/cjs/loader:1137:19)
      at require (node:internal/modules/helpers:121:18)
      at A (/usr/lib/node_modules/blade-formatter/node_modules/@shufo/tailwindcss-class-sorter/dist/main.js:1:2018)
      at v (/usr/lib/node_modules/blade-formatter/node_modules/@shufo/tailwindcss-class-sorter/dist/main.js:1:1580)
}
```

While formatting a blade file, I get the above error. Why does it look for `tailwind.config.js` when it is a blade file?

### Expected Behavior

It should not have an error

### Actual Behavior

There was an error

### Additional Context

# blade-formatter --version
1.32.12

**Comment by bilogic** [comment]
I added `--tailwindcss-config-path ~/tailwind.config.js` and fixed it. Thank you.
