### ISSUE TITLE
[Feature]: None zero exit status on errors

### ISSUE THREAD

**Issue by AJenbo** [shufo/blade-formatter#893]
### Description

For automation it would be nice if the check would exit  with a non zero status if there are any errors found during the process so that scripts can easily flag the issue (git hub action for example)

### Suggested Solution

You can run `$?` to show the exit status of a script

**Comment by shufo** [comment]
Thanks for the suggestion.
blade-formatter already raises a non-zero status if there are format check failures or any exceptions, such as with Prettier. So you can use this package as a format checker on your CI.

```
 $  ./bin/blade-formatter.js test.blade.php -c
Check formatting...
test.blade.php

Above file(s) are formattable. Forgot to run formatter? Use --write option to overwrite.
 $  echo $?
1

 $  ./bin/blade-formatter.js test.blade.php -c
Check formatting...

All matched files are formatted!

Errors:

{
  path: 'test.blade.php',
  message: "Parse Error : syntax error, unexpected '!', expecting ';' on line 1\n" +
    '> 1 | <?php echo !!aaa!! ?>\n' +
    '    |                ^',
  error: SyntaxError: Parse Error : syntax error, unexpected '!', expecting ';' on line 1
  > 1 | <?php echo !!aaa!! ?>
      |                ^
      at I.raiseError (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:72270)
      at I.error (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:72912)
      at I.expectEndOfStatement (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:74017)
      at I.read_statement (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:60057)
      at I.read_top_statement (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:56856)
      at I.read_start (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:89186)
      at I.parse (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:71648)
      at ao.parseCode (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:120569)
      at Object.uo [as parse] (/home/shuhei/develop/blade-formatter21/node_modules/@prettier/plugin-php/standalone.js:1:121457)
      at ao (/home/shuhei/develop/blade-formatter21/node_modules/prettier/standalone.js:22:13314) {
    fileName: 'eval',
    loc: { start: [Object] },
    codeFrame: '> 1 | <?php echo !!aaa!! ?>\n    |                ^'
  }
}

 $  echo $?
1
```

**Comment by AJenbo** [comment]
Oh, not sure why i didn't work at first. Well thanks for heads up.
